"""Pure render helpers for the medargue explainability dashboard (no Streamlit import).

Every function here is a pure data/graph transform so the panels unit-test without launching Streamlit
(ui-spec §8). `app.py` wires Streamlit widgets around these. Status→colour is a static literal map
(ui-spec §2/§4); colour is never the only signal — accepted nodes are also bold with a green border.
"""

from __future__ import annotations

from typing import Any

import graphviz

from src.data.chexpert import CHEXPERT_LABELS, FOCUS_5

# Short disclaimer (reused from the argumentation layer) + the full UI banner (ui-spec §5).
SHORT_DISCLAIMER = "Research prototype — not clinical advice."
UI_DISCLAIMER = (
    "⚠ Research prototype — not clinical advice. Outputs are generated by a multi-agent "
    "argumentation system on surrogate data for academic evaluation. Do not use for real clinical "
    "decisions."
)

# Status → colour (WCAG-AA tuned, ui-spec §2). Static map — never build colour strings at runtime.
STATUS_COLORS: dict[str, str] = {
    "accepted": "#15803D",  # in the preferred extension (survives debate)
    "attack": "#DC2626",  # attack edge / refuted
    "undecided": "#D97706",
    "neutral": "#3B82F6",
}

# OIDP: the modalities each agent can NOT see (reinforces the partitioning story, ui-spec §4).
AGENT_BLIND: dict[str, list[str]] = {
    "vision": ["report", "ehr"],
    "report": ["image", "ehr"],
    "clinical": ["image", "report"],
}

_AGENT_TITLE = {"vision": "Vision (CXR)", "report": "Report (text)", "clinical": "Clinical (EHR)"}


def disclaimer_text() -> str:
    return UI_DISCLAIMER


def recommendation(output: Any) -> str:
    """The headline pathology recommendation (first predicted focus label, else 'No Finding')."""
    for label in FOCUS_5:
        if label in output.predicted_labels:
            return label
    return next(iter(sorted(output.predicted_labels)), "No Finding")


def kpi_cards(output: Any) -> list[dict[str, str]]:
    """KPI row: recommendation, confidence, #arguments, #attacks, debate rounds (ui-spec §4)."""
    state = output.debate_state or {}
    conf = output.confidence
    return [
        {"label": "Recommendation", "value": recommendation(output)},
        {"label": "Confidence", "value": f"{conf:.0%}" if conf is not None else "n/a"},
        {"label": "Arguments", "value": str(len(output.arguments))},
        {"label": "Attacks", "value": str(len(state.get("attacks", [])))},
        {"label": "Debate rounds", "value": str(state.get("round", 0))},
    ]


def modality_panel(agent: str, arguments: list[Any]) -> dict[str, Any]:
    """One agent's panel: its claims + cited evidence + Walton scheme, and what it could NOT see."""
    claims = [
        {"claim": a.claim, "evidence": list(a.evidence), "scheme": a.scheme}
        for a in arguments
        if a.agent == agent
    ]
    return {
        "title": _AGENT_TITLE.get(agent, agent),
        "agent": agent,
        "claims": claims,
        "blind_to": AGENT_BLIND.get(agent, []),
    }


def build_argument_graph(
    arguments: list[Any], attacks: list[Any], extension_claims: set[str]
) -> graphviz.Digraph:
    """Dung argument graph: nodes = arguments (accepted = green+bold), edges = attacks (red arrows).

    `extension_claims` = claims in the preferred extension (the 'winning' set).
    """
    dot = graphviz.Digraph("argument_graph")
    dot.attr("graph", rankdir="LR", bgcolor="transparent")
    dot.attr("node", shape="box", style="rounded,filled", fontname="Fira Sans")

    claim_to_id: dict[str, str] = {}
    for i, arg in enumerate(arguments):
        node_id = f"n{i}"
        claim_to_id.setdefault(arg.claim, node_id)
        accepted = arg.claim in extension_claims
        label = arg.claim if len(arg.claim) <= 40 else arg.claim[:37] + "…"
        dot.node(
            node_id,
            label=f"[{arg.agent}]\n{label}",
            color=STATUS_COLORS["accepted"] if accepted else "#94A3B8",
            penwidth="3" if accepted else "1",
            fillcolor="#DCFCE7" if accepted else "#FFFFFF",
            fontcolor="#1E3A8A",
        )
    for atk in attacks:
        src = claim_to_id.get(atk.source_claim)
        dst = claim_to_id.get(atk.target_claim)
        if src and dst:
            dot.edge(src, dst, color=STATUS_COLORS["attack"], arrowhead="vee", penwidth="2")
    return dot


def pathology_rows(predicted: set[str]) -> list[dict[str, Any]]:
    """All 14 CheXpert labels with {predicted, focus} - the text/table fallback for the graph (a11y §7)."""
    focus = set(FOCUS_5)
    return [
        {"label": label, "predicted": label in predicted, "focus": label in focus}
        for label in CHEXPERT_LABELS
    ]
